Feat: consume per partition
withthegrid/node-rdkafka pull request #2
Opened 2024-01-11 10:22 UTC by martijnimhoff

Pull request checklist:

- [x] Include new test cases (either end-to-end or unit tests) with your change.
  > Existing test cases do not include consuming via the standard API. So did not make those for this case.
- [x] Follow our style guides.
- [x] Make sure all tests are still passing and the linter does not report any issues.
  > Current master has only quite a few linter errors. I made sure to not add any new errors and I've fixed a few.
- [x] End files with a new line.
- [x] Document the new code in the comments (if it is JavaScript) so the documentation generator can update the reference documentation.
- [x] Avoid platform-dependent code.
- [x] Note: If making modifications to the underlying C++, please use built-in precompiler directives to detect such platform specificities. Use Nan whenever possible to abstract node/v8 version incompatibility.
- [x] Make sure your branch is up to date and rebased.
- [x] Squash extraneous commits unless their history truly adds value to the library.

2024-01-11 10:25 UTC, martijnimhoff commented
@jdbruijn @everhardt Could you review before we submit the PR to Blizzard?

2024-01-11 10:33 UTC, jdbruijn commented
Yes, but will be next week.

2024-01-14 21:12 UTC, everhardt commented
This implementation allows consuming some partitions individually and leaving the others in the global queue. The current way of doing that has a few weird consequences:
1. once you called `.consume(..)` for a specific partition, it cannot be brought back into the `consumer.consume` of the global queue. I practice I don't think this is an issue and a small function `.forwardToGlobalQueue(partitionId)` can always be added
2. if you don't manually call `.consume(..)` on the global queue you won't get any rebalance events. The alternative of doing this automatically somewhere seems less attractive to me
3. if you don't listen out the rebalance events, some partitions will remain be in the global queue and will thus be part of the callback of the `.consume(..)` call of the global queue, probably even in flowing mode.

2024-01-23 15:51 UTC, everhardt commented
@martijnimhoff What's the status of this one?

2024-01-23 16:06 UTC, jdbruijn commented
AFAIK waiting for my review, then we can merge it here and start using this in the Teleport code, as well as opening an PR in the upstream. Review in progress BTW

![image](https://github.com/withthegrid/node-rdkafka/assets/62570005/3c8e5eaa-4d57-464e-a637-bd30481e4139)

2024-01-23 16:18 UTC, jdbruijn requested changes

2024-01-23 16:18 UTC, jdbruijn commented on lib/kafka-consumer.js
> + * @param {number} topic - Name of topic to read
This is a string.

2024-01-23 16:18 UTC, jdbruijn commented on src/workers.cc
> +    m_timeout_ms);
Did this change come from the linter (ccplint.py)? If not, this should probably not be changed, doesn't hurt either of course as it's just styling.

2024-01-23 16:18 UTC, jdbruijn commented on src/workers.cc
> +          // messages, so we return an EOF message
Did this change come from the linter (ccplint.py)? If not, this should probably not be changed, doesn't hurt either of course as it's just styling.

2024-01-23 16:18 UTC, jdbruijn commented on src/kafka-consumer.cc
> +
Remove new-line to stay in line with the other code, e.g. below at L1181.

2024-01-23 16:18 UTC, jdbruijn commented on lib/kafka-consumer.js
> + * consumption of other partitions.
```suggestion
 * Can be useful if the consume performance differs per partition. Consuming
 * per partition could prevent slow performance on one partition from affecting
 * the consumption of other partitions.
```

2024-01-23 16:18 UTC, jdbruijn commented on src/workers.cc
> + * @brief KafkaConsumer get messages worker.
```suggestion
 * @brief KafkaConsumer get messages per partition worker.
```

2024-01-24 06:51 UTC, martijnimhoff commented on src/workers.cc
> +    m_timeout_ms);
This is indeed a lint fix. Current master has quite a few linter errors. I made sure to not add any new errors and I've fixed a few.

2024-01-24 06:51 UTC, martijnimhoff commented on src/workers.cc
> +          // messages, so we return an EOF message
This is indeed a lint fix. Current master has quite a few linter errors. I made sure to not add any new errors and I've fixed a few.

2024-01-24 06:53 UTC, martijnimhoff commented on src/kafka-consumer.cc
> +
Done.

2024-01-24 08:48 UTC, merged

2024-01-24 09:11 UTC, everhardt commented
@martijnimhoff how did you address my [third point](https://github.com/withthegrid/node-rdkafka/pull/2#issuecomment-1891073659)?

2024-01-24 10:07 UTC, martijnimhoff commented
> if you don't listen out the rebalance events, some partitions will remain be in the global queue and will thus be part of the callback of the .consume(..) call of the global queue, probably even in flowing mode.

It's a strange situation, but perhaps a use-case would exist in which you want to control the consumption per partition of just a few partitions and the remaining partitions could be consumed via the callback. So I would say it's an odd, but  desired behavior. I'm actually now sure if this will function correctly... I'll do a test to see what happens.

2024-01-24 12:56 UTC, martijnimhoff commented
@everhardt it indeed results in data loss.

When the consume per partition starts after a timeout of 1s. All the messages in the partition (50) are already consumed by the regular .consume queue. This can be seen in the `data` event and in the callback. 

Perhaps i can see if can create a consumer configuration which disables the forwarding to the general queue for all partitions. Something like this: 

```
var consumer = new KafkaNode.KafkaConsumer({
   ...
  'consume_per_partition': true,
}, {
   ...
});
```