feat: add method to disable queue forwarding
withthegrid/node-rdkafka pull request #3
Opened 2024-02-19 13:06 UTC by martijnimhoff

Fixes: https://github.com/withthegrid/teleport/issues/920

2024-02-20 11:08 UTC, jdbruijn requested changes

2024-02-20 11:08 UTC, jdbruijn commented on package.json
> +  "version": "v2.19.0",
Should not be part of the PR.

2024-02-20 15:32 UTC, jdbruijn commented on package.json
> +  "version": "v2.19.0",
Still not quite it 😄 the file should not be part of this PR at all, so need to set version bak to 2.18.0

![image](https://github.com/withthegrid/node-rdkafka/assets/62570005/1753d4fb-e093-4f9e-b12f-0555f53e598b)

2024-02-21 10:42 UTC, martijnimhoff commented on package.json
> +  "version": "v2.19.0",
Hmm whoops. It's now gone.

2024-02-21 11:28 UTC, merged